### ISSUE TITLE
Cannot individual play songs from an album

### ISSUE THREAD

**Issue by Ransomwave** [tomer8007/spotify-web-ads-remover#15] opened 2023-07-09 21:37 UTC
Recently I noticed you cannot, lets say, play the 5th song in an album. It will not skip the current song at all and wont do anything.
The Chrome devtools gives back a 403 error.

`POST https://gew1-spclient.spotify.com/connect-state/v1/player/command/from/9243312d3a8b3702f4d082ad2e93f3a5b0c68705/to/9243312d3a8b3702f4d082ad2e93f3a5b0c68705 403`
![image](https://github.com/tomer8007/spotify-web-ads-remover/assets/63156992/e7074585-3a15-45c9-9f36-cc1ec1e006b8)

https://github.com/tomer8007/spotify-web-ads-remover/assets/63156992/b0e58bff-8bdb-41a4-a393-d7f8e5889de8

**Comment by tomer8007** [comment] 2023-07-10 00:53
Thanks for the detailed report. I was able to reproduce this.

It seems Spotify doesn't let us change the state machine like that for some reason:

![image](https://github.com/tomer8007/spotify-web-ads-remover/assets/11458759/c8c94acc-35cd-4763-8d31-7e1cf47a5c76)

I will try to look more into that.

**Comment by tomer8007** [comment] 2024-02-02 14:12
@Ransomwave I think this bug is fixed now. Am I correct?

**Comment by tomer8007** [comment] 2024-03-01 22:23
Closing because it seems fixed for me.

**Closed by tomer8007** 2024-03-01 22:23 UTC
Labels: bug
