### ISSUE TITLE
Stops playing after failure to update state, happens randomly 

### ISSUE THREAD

**Issue by Alvin-He** [tomer8007/spotify-web-ads-remover#17] opened 2024-01-22 07:47 UTC
After listening to a playlist for a good while, the track will randomly get stuck after a song finishes. [Ref 1](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/fb42a14b-55a5-4c1b-981c-8589be678988) Pressing the next button does not work, the only way to proceed is to manually press play on the next song, but instead of the playing that song, it plays the ad (while showing the song name & icon, time is shown as the ad's). [Ref 2](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/23252a5e-e1f5-454b-9a96-225ada4c6e0a) The player then works normally with out any errors until this happens again.

I looked through the console logs and net work logs and it seems to have to do with some access token expiring resulting in a 401 when updating the state. I won't try to explain everything in words, the console log and network HAR file are at the bottom.

I been having this issue for multiple months now, initially I thought it was due to a spotify update that broke something and waited for a patch, but apparently this haven't been reported. It might also be the cause of issue https://github.com/tomer8007/spotify-web-ads-remover/issues/14 

Console Log file, initial error (I think that's the initial error) starting on line 156:  
[open.spotify.com-1705908195262.log](https://github.com/tomer8007/spotify-web-ads-remover/files/14006563/open.spotify.com-1705908195262.log)

Console Network Har log file (the network request corresponding to the initial error is the request named state that 401ed): 
[open.spotify.com.har](https://fmxal.mooo.com/open.spotify.com.har)

Browser: Opera GX LVL5 (core: 106.0.4998.49) -- It's chromium so I doubt it's the browser's fault  
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0
OS: Windows 10

Reference image 1: 
![spoti_ads_issue_ref_1](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/fb42a14b-55a5-4c1b-981c-8589be678988)
Reference image 2: 
![spoti_ads_issue_ref2](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/23252a5e-e1f5-454b-9a96-225ada4c6e0a)

**Comment by Alvin-He** [comment] 2024-01-22 07:50
just a note: had it happen again after I manually skipped the song, but this time it doesn't show any errors or show any 401ed state requests

**Comment by tomer8007** [comment] 2024-02-02 14:11
> seems like the state requests fail randomly when this bug happens, 

Are they failing because of 401 Errors, e.g access token refreshing fails?

**Comment by Alvin-He** [comment] 2024-02-07 04:01
Actually it seems to be that if the request to `https://<spclient some subdomain>.spotify.com/track-playback/v1/devices/<device-id>/state` fails, the bug happens 

Cause right now I'm not getting these 401 errors anymore, instead it's a different `spclient` server that's returning 502 and 504s

![Screenshot 2024-02-06 200006](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/4c046ef6-e2e2-4439-b2af-4444e4d4cf78)

![image](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/bf8c8e14-a479-4c9d-8cee-652e30edbf73)

**Comment by Alvin-He** [comment] 2024-02-07 04:09
actually, I'm still getting same 401s from a url similar to the one that I just mentioned and the bug happened immediately after that. So it's probably related that specific request failing.

**Comment by Alvin-He** [comment] 2024-02-07 07:45
oh and em, this happened? 
![image](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/a7bfbecc-73ac-46d8-968c-2635f3f9b329)

**Comment by tomer8007** [comment] 2024-02-08 23:19
I see we have an internal timeout grpc error inside Spotify servers, which I'm not sure what's causing it exactly.
Does the retry mechanism I added there seem to make the next `state` request return `200`?
Do you think adding more retries / more access token refreshes will fix it?

**Comment by Alvin-He** [comment] 2024-02-08 23:45
> Does the retry mechanism I added there seem to make the next state request return 200?

I didn’t proceed with the debugger so actually don’t exactly know how it affects the next state request😅  

the network logs seems to show that the next state request is Ok so the retry mechanism is probably doing it’s job

    
    
Adding more retries might help. Have you been able to replicate this?

**Comment by tomer8007** [comment] 2024-02-08 23:50
> Have you been able to replicate this?

Not that I'm sure about that. As you saw in the comments I did encounter a `502` in the past, but since this bug is pretty random it's hard for me to reproduce it. I can try to skip a lot of songs or listen a lot but I don't know if this is the way to trigger this.

**Comment by Alvin-He** [comment] 2024-02-15 02:01
For me it's just playing a playlist for around 20-30 mins and then the bug would happen. I think happens when you listen a lot. 

I'll see if I can add code to do more refreshes this weekend and see if that helps. 

Sorry for the late response

Also, idk if this is related, but I'm now ***Sometimes*** also getting these errors after the bug happens
![image](https://github.com/tomer8007/spotify-web-ads-remover/assets/71620129/3381b537-cda8-4189-b8ea-f44b017fc284)

**Comment by tomer8007** [comment] 2024-03-01 22:29
@Alvin-He I also encountered the "could not find the next ad-free state" errors recently, I think it's because Spotify changed some stuff in the states of ads. Seems to be fixed for bug after I commited b5e1a6932c1e2dff9fe3d913316ebaf6fa4e9110.

**Comment by tomer8007** [comment] 2024-05-17 11:20
@Alvin-He I'm closing this for now, if the problem persists you can re-open.

**Closed by tomer8007** 2024-05-17 11:20 UTC
Labels: bug
